install.packages("ISLR") # installing the ISLR package
library(ISLR)
help("Auto")
dim(Auto)
data(Auto)
str(Auto)
names(Auto)
summary(Auto)
head(Auto)
fivenum(Auto$mpg)
boxplot(Auto$mpg)
hist(Auto$mpg)
hist(Auto$horsepower)
mode(Auto$mpg)
